name: CI

on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node Version
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"
      - run: |
          npm ci
          npm run format:check
          npm test -- --coverage
        env:
            CI: true
